export const GET_PROJECTS_BY_LOCATION = 'CHOOSING_PROJECT/GET_PROJECTS_BY_LOCATION';
export const GET_ALL_CITIES = 'CHOOSING_PROJECT/GET_ALL_CITIES';
export const CHANGE_CURRENT_CITY = 'CHOOSING_PROJECT/CHANGE_CURRENT_CITY';
export const SET_CURRENT_LOCATION = 'CHOOSING_PROJECT/SET_CURRENT_LOCATION';
